import path from 'node:path';
import { mkdir, writeFile } from 'node:fs/promises';
import { parseBusinessTestCases } from '../parser/test-case-parser';
import { extractLocatorCatalog } from '../locator-engine/locator-extractor';
import type {
  AiTestDefinition,
  LocatorCatalog,
  LocatorCatalogEntry,
  StructuredTestStep,
} from '../shared/types';
import {
  escapeForSingleQuotedString,
  readJsonFile,
  slugify,
  toPascalCase,
  writeJsonFile,
} from '../shared/utils';

interface GenerateOptions {
  inputPath: string;
  baseUrl: string;
  outputDir: string;
  catalogPath: string;
  scanLiveSite: boolean;
  automationMode: 'automated' | 'all';
}

const DEFAULT_TEST_DATA: Record<string, string> = {
  validEmail: 'qa@example.com',
  validPassword: 'CorrectHorseBatteryStaple1!',
  validName: 'QA Automation User',
  validMessage: 'Generated by the AI QA automation framework.',
  value: 'test value',
};

export async function generatePlaywrightSpecs(options: GenerateOptions): Promise<void> {
  const parsedDefinitions = await parseBusinessTestCases(options.inputPath);
  const definitions =
    options.automationMode === 'all'
      ? parsedDefinitions
      : parsedDefinitions.filter((definition) => definition.automationMode === 'automated');
  await mkdir(options.outputDir, { recursive: true });
  await writeJsonFile('qa-engine/ai/generated-tests/structured-test-definitions.json', definitions);

  const catalog = options.scanLiveSite
    ? await extractLocatorCatalog({ baseUrl: options.baseUrl, outputPath: options.catalogPath })
    : await readJsonFile<LocatorCatalog>(options.catalogPath);

  for (const definition of definitions) {
    const fileName = `${slugify(definition.module)}-${slugify(definition.scenario)}.generated.spec.ts`;
    await writeFile(path.join(options.outputDir, fileName), renderSpec(definition, catalog), 'utf8');
  }
}

function renderSpec(definition: AiTestDefinition, catalog: LocatorCatalog): string {
  // Resolve locator entries during generation so emitted specs stay readable and deterministic.
  const matchedEntries = definition.steps.map((step) =>
    shouldUseLocator(step) ? matchCatalogEntry(step, catalog) : undefined,
  );
  const entryConstants = matchedEntries
    .map((entry, index) =>
      entry
        ? `const locatorEntry${index + 1} = ${JSON.stringify(entry, null, 2)} as LocatorCatalogEntry;`
        : undefined,
    )
    .filter(Boolean)
    .join('\n\n');
  const className = `${toPascalCase(definition.module)}${toPascalCase(definition.scenario)}Page`;
  const renderedSteps = definition.steps
    .map((step, index) => renderStep(step, index, matchedEntries[index]))
    .join('\n\n');
  const tags = definition.tags.map((tag) => `@${tag}`).join(' ');

  return `import { expect, test } from '@playwright/test';
import type { LocatorCatalogEntry } from '../../../core/shared/types';
import { recordLocatorRepair } from '../../../core/self-healing/repair-selectors';
import { SelfHealingLocator } from '../../fixtures/self-healing';

/**
 * AI Metadata
 * id: ${definition.id}
 * module: ${definition.module}
 * scenario: ${definition.scenario}
 * priority: ${definition.priority}
 * riskLevel: ${definition.riskLevel}
 * tags: ${tags}
 * generatedAt: ${definition.generatedAt}
 * confidenceScore: ${definition.confidenceScore}
 */

${entryConstants}

class ${className} {
  constructor(private readonly page: import('@playwright/test').Page) {}

  locator(entry: LocatorCatalogEntry) {
    return new SelfHealingLocator(this.page, entry, async (repair) => {
      if (repair.repaired) {
        test.info().annotations.push({
          type: 'locator-repair',
          description: \`\${entry.key}: \${repair.reason} confidence=\${repair.confidenceScore}\`,
        });
      }
      await recordLocatorRepair('qa-engine/ai/locator-catalog/locators.json', entry.key, repair);
    });
  }
}

test.describe('${escapeForSingleQuotedString(definition.module)}', () => {
  test('${escapeForSingleQuotedString(definition.scenario)} ${tags}', async ({ page }) => {
    const app = new ${className}(page);

${indent(renderedSteps, 4)}
  });
});
`;
}

function renderStep(step: StructuredTestStep, index: number, entry: LocatorCatalogEntry | undefined): string {
  const comment = `// ${step.id}: ${step.businessText}`;
  const locatorRef = `locatorEntry${index + 1}`;
  const fallbackTarget = escapeForSingleQuotedString(step.targetHint || step.businessText);

  if (step.action === 'navigate') {
    return `${comment}
await page.goto('/', { waitUntil: 'networkidle' });
await expect(page).toHaveURL(/\\/$/);`;
  }

  if (step.action === 'fill') {
    const valueKey = step.valueHint || 'value';
    const value = DEFAULT_TEST_DATA[valueKey] || DEFAULT_TEST_DATA.value;
    if (entry) {
      return `${comment}
await app.locator(${locatorRef}).fill('${escapeForSingleQuotedString(value)}');`;
    }
    return `${comment}
await page.getByLabel('${fallbackTarget}').or(page.getByPlaceholder('${fallbackTarget}')).fill('${escapeForSingleQuotedString(value)}');`;
  }

  if (step.action === 'click') {
    if (entry) {
      return `${comment}
await app.locator(${locatorRef}).click();`;
    }
    return `${comment}
await page.getByRole('button', { name: /${escapeRegex(fallbackTarget)}/i }).or(page.getByText('${fallbackTarget}')).click();`;
  }

  if (step.action === 'assertVisible') {
    if (entry) {
      return `${comment}
await app.locator(${locatorRef}).expectVisible();`;
    }
    return `${comment}
await expect(page.getByText('${fallbackTarget}', { exact: false })).toBeVisible();`;
  }

  return `${comment}
await test.step('${escapeForSingleQuotedString(step.businessText)}', async () => {
  // Manual review recommended: the parser could not infer a deterministic Playwright action.
});`;
}

function shouldUseLocator(step: StructuredTestStep): boolean {
  return step.action === 'fill' || step.action === 'click' || step.action === 'assertVisible';
}

function matchCatalogEntry(
  step: StructuredTestStep,
  catalog: LocatorCatalog,
): LocatorCatalogEntry | undefined {
  const hint = (step.targetHint || step.businessText).toLowerCase();
  // Favor exact semantic matches, but allow partial matches for business-language test steps.
  const scored = catalog.entries
    .map((entry) => {
      return { entry, score: scoreCatalogEntry(hint, entry) };
    })
    .filter((candidate) => candidate.score >= 0.35)
    .sort((a, b) => b.score - a.score);

  return scored[0]?.entry;
}

function scoreCatalogEntry(hint: string, entry: LocatorCatalogEntry): number {
  const shortText = entry.text && entry.text.length <= 80 ? entry.text : undefined;
  const exactFields = [entry.label, entry.testId, entry.ariaLabel, entry.placeholder, entry.name, shortText]
    .filter(Boolean)
    .map((value) => String(value).toLowerCase());

  if (exactFields.some((value) => value === hint)) return 1;
  if (exactFields.some((value) => value.includes(hint) || hint.includes(value))) return 0.9;

  const semanticFields = [
    entry.label,
    entry.testId,
    entry.ariaLabel,
    entry.placeholder,
    entry.name,
    shortText,
    entry.component,
  ]
    .filter(Boolean)
    .join(' ')
    .toLowerCase();

  return scoreText(hint, semanticFields);
}

function scoreText(hint: string, candidate: string): number {
  const hintWords = hint.split(/\W+/).filter((word) => word.length > 2);
  if (hintWords.length === 0) return 0;
  const matches = hintWords.filter((word) => candidate.includes(word)).length;
  return matches / hintWords.length;
}

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function indent(value: string, spaces: number): string {
  return value
    .split('\n')
    .map((line) => `${' '.repeat(spaces)}${line}`)
    .join('\n');
}
